In [1]:
from src.models.layers import LipsLayers
import torch
import importlib

In [47]:
importlib.reload(LipsLayers)

<module 'src.models.layers.LipsLayers' from '/orcd/data/jhm/001/om2/rphess/projects/github.com/model_metamers_pytorch/src/models/layers/LipsLayers.py'>

In [30]:
test_linear = LipsLayers.LipsLinear(4, 16, w_max=2.0, projection="orthogonalize")

In [31]:
torch.svd(test_linear.weight)

torch.return_types.svd(
U=tensor([[-0.2471, -0.5136,  0.0350,  0.2120],
        [ 0.2531,  0.2801,  0.0860,  0.1606],
        [-0.0106,  0.0619,  0.1252, -0.3199],
        [ 0.0168,  0.0975,  0.0544, -0.0304],
        [-0.2379,  0.3907, -0.4493,  0.0638],
        [-0.4153,  0.1761,  0.0768,  0.1036],
        [ 0.5994, -0.3093, -0.0867,  0.0853],
        [ 0.2595, -0.0631, -0.0844, -0.1909],
        [-0.0542,  0.1109,  0.1786,  0.5112],
        [ 0.1112,  0.4383,  0.1915,  0.1946],
        [-0.1776,  0.0590,  0.0434, -0.0175],
        [ 0.1109, -0.1036,  0.1206,  0.6453],
        [ 0.3305,  0.3395,  0.1132, -0.0673],
        [-0.1561, -0.1192,  0.0138, -0.0562],
        [ 0.1584,  0.1001, -0.5328,  0.0998],
        [ 0.0298,  0.0552,  0.6071, -0.1839]], grad_fn=<LinalgSvdBackward0>),
S=tensor([4.0000, 4.0000, 4.0000, 4.0000], grad_fn=<LinalgSvdBackward0>),
V=tensor([[ 0.0000, -1.0000, -0.0000, -0.0000],
        [-0.9712, -0.0000,  0.2382,  0.0000],
        [-0.2377,  0.0000, -0.9693, -0

In [32]:
test_linear.weight.data += torch.randn_like(test_linear.weight.data) * 0.1

In [33]:
torch.svd(test_linear.weight)

torch.return_types.svd(
U=tensor([[-0.1260,  0.4464, -0.0418, -0.3821],
        [-0.0888, -0.3566,  0.0674, -0.0187],
        [ 0.0287,  0.0504,  0.0943,  0.3285],
        [ 0.0167, -0.0765,  0.0654,  0.0807],
        [ 0.5541, -0.2565, -0.2570, -0.0617],
        [ 0.3726,  0.0772,  0.2550, -0.1502],
        [-0.5673, -0.0851, -0.3224, -0.0678],
        [-0.2198, -0.0431, -0.2338,  0.2089],
        [-0.0047, -0.2500,  0.2775, -0.4400],
        [-0.0015, -0.4489,  0.2460, -0.0213],
        [ 0.1629,  0.0330,  0.1056, -0.0131],
        [-0.2312, -0.1989,  0.1081, -0.5798],
        [-0.1163, -0.4241,  0.0238,  0.2253],
        [ 0.0554,  0.2277,  0.0314, -0.0479],
        [ 0.1323, -0.2169, -0.4798, -0.0745],
        [-0.2122,  0.0303,  0.5466,  0.2750]], grad_fn=<LinalgSvdBackward0>),
S=tensor([4.3627, 4.1544, 3.9636, 3.7686], grad_fn=<LinalgSvdBackward0>),
V=tensor([[-0.4615,  0.7867, -0.2609, -0.3164],
        [ 0.6712,  0.4985,  0.5217, -0.1697],
        [ 0.5799,  0.0398, -0.8098, -0

In [34]:
test_linear.project_()

In [35]:
torch.svd(test_linear.weight)

torch.return_types.svd(
U=tensor([[-0.3820,  0.1260, -0.0419,  0.4464],
        [-0.0187,  0.0888,  0.0675, -0.3565],
        [ 0.3285, -0.0287,  0.0943,  0.0504],
        [ 0.0807, -0.0167,  0.0654, -0.0765],
        [-0.0617, -0.5541, -0.2569, -0.2565],
        [-0.1502, -0.3726,  0.2551,  0.0772],
        [-0.0678,  0.5672, -0.3224, -0.0851],
        [ 0.2089,  0.2198, -0.2338, -0.0431],
        [-0.4400,  0.0048,  0.2775, -0.2499],
        [-0.0213,  0.0015,  0.2461, -0.4489],
        [-0.0131, -0.1629,  0.1056,  0.0330],
        [-0.5798,  0.2312,  0.1081, -0.1989],
        [ 0.2253,  0.1163,  0.0239, -0.4241],
        [-0.0479, -0.0554,  0.0313,  0.2277],
        [-0.0745, -0.1323, -0.4797, -0.2170],
        [ 0.2750,  0.2123,  0.5465,  0.0304]], grad_fn=<LinalgSvdBackward0>),
S=tensor([3.9968, 3.9934, 3.9881, 3.9870], grad_fn=<LinalgSvdBackward0>),
V=tensor([[-0.3164,  0.4615, -0.2611,  0.7866],
        [-0.1697, -0.6711,  0.5217,  0.4987],
        [-0.0792, -0.5800, -0.8098,  0

In [36]:
test_input = torch.randn(1, 4)
test_linear(test_input)

tensor([[ 1.3289, -1.9763, -0.3197, -0.5121,  3.2217,  1.2984, -1.9196, -0.4955,
         -1.7289, -2.5809,  0.5504, -1.9450, -2.3566,  0.9853,  2.0485, -3.5545]],
       grad_fn=<MmBackward0>)

# Testing the LipsConv2d layer

In [48]:
test_conv = LipsLayers.LipsConv2d(4, 16, 3, w_max=2.0, projection="spectral_normalize")

In [49]:
test_conv.weight.data.shape

torch.Size([16, 4, 3, 3])

In [50]:
for i in range(test_conv.weight.data.shape[2]):
    for j in range(test_conv.weight.data.shape[3]):
        slice_ij = test_conv.weight.data[:, :, i, j]
        u, s, v = torch.svd(slice_ij)
        print(s)

tensor([0.4495, 0.4280, 0.3022, 0.1957])
tensor([0.4444, 0.3091, 0.2676, 0.1921])
tensor([0.4444, 0.3405, 0.2176, 0.1942])
tensor([0.4537, 0.4409, 0.3487, 0.2148])
tensor([0.4444, 0.3553, 0.3382, 0.2087])
tensor([0.4541, 0.4291, 0.3502, 0.2653])
tensor([0.4444, 0.2954, 0.2702, 0.1997])
tensor([0.4444, 0.2840, 0.2720, 0.1884])
tensor([0.4444, 0.3752, 0.3009, 0.2449])


In [ ]:
test_conv.weight.data += torch.randn_like(test_conv.weight.data) * 0.1
for i in range(test_conv.weight.data.shape[2]):
    for j in range(test_conv.weight.data.shape[3]):
        slice_ij = test_conv.weight.data[:, :, i, j]
        u, s, v = torch.svd(slice_ij)
        print(s)

tensor([0.6738, 0.6145, 0.3983, 0.3005])
tensor([0.6182, 0.5474, 0.4778, 0.3476])
tensor([0.7774, 0.5657, 0.4180, 0.3502])
tensor([0.6775, 0.6315, 0.4777, 0.4596])
tensor([0.5794, 0.5109, 0.4138, 0.3342])
tensor([0.7675, 0.5928, 0.5146, 0.3822])
tensor([0.5813, 0.5388, 0.4052, 0.3414])
tensor([0.6719, 0.5382, 0.4511, 0.3402])
tensor([0.6056, 0.5537, 0.4420, 0.3229])


In [52]:
test_conv.project_()
for i in range(test_conv.weight.data.shape[2]):
    for j in range(test_conv.weight.data.shape[3]):
        slice_ij = test_conv.weight.data[:, :, i, j]
        u, s, v = torch.svd(slice_ij)
        print(s)

tensor([0.4445, 0.4054, 0.2628, 0.1982])
tensor([0.4457, 0.3947, 0.3445, 0.2506])
tensor([0.4444, 0.3234, 0.2390, 0.2002])
tensor([0.4540, 0.4232, 0.3202, 0.3080])
tensor([0.4445, 0.3920, 0.3175, 0.2564])
tensor([0.4444, 0.3433, 0.2980, 0.2213])
tensor([0.4462, 0.4136, 0.3110, 0.2621])
tensor([0.4444, 0.3560, 0.2984, 0.2250])
tensor([0.4466, 0.4084, 0.3260, 0.2381])
